import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import yfinance as yf
import warnings
import time
from matplotlib.backends.backend_pdf import PdfPages
import io
import sys
import os # Import os for environment variables
import textwrap # Import the textwrap module

# --- Google Gemini API Integration ---
import google.generativeai as genai

# Configure the API key
# IMPORTANT: Replace 'YOUR_GEMINI_API_KEY' with your actual API key,
# or even better, set it as an environment variable (e.g., GOOGLE_API_KEY)
# and load it like this:
# API_KEY = os.getenv("GOOGLE_API_KEY")
# if not API_KEY:
#    raise ValueError("GOOGLE_API_KEY environment variable not set. Please set your Gemini API key.")

API_KEY = os.getenv("GOOGLE_API_KEY")
if not API_KEY:
    raise ValueError("GOOGLE_API_KEY environment variable not set. Please set your Gemini API key.")

genai.configure(api_key=API_KEY)

# Function to call Google Gemini API
def get_gemini_summary(portfolio_data_string: str) -> str:
    """
    Calls the Google Gemini API to summarize portfolio health.

    Args:
        portfolio_data_string (str): A string containing relevant portfolio data
                                     to be fed to the LLM.

    Returns:
        str: A summary of the portfolio's health generated by Gemini,
             or an error message if the API call fails.
    """
    try:
        # Choose a model. gemini-1.5-flash is generally good for speed and cost.
        # For more complex reasoning, consider gemini-1.5-pro.
        model = genai.GenerativeModel('gemini-1.5-flash')

        # Craft the prompt for the LLM
        prompt = (
            "Analyze the following stock portfolio data and provide a concise summary "
            "of its overall health, key characteristics, and any notable observations. "
            "Focus on diversification, risk (beta), potential income (dividend yield), and capitalization.\n\n"
            f"Portfolio Data:\n{portfolio_data_string}\n\n"
            "Summary:"
        )

        print("\n  Calling Google Gemini API for summary... (This may take a moment)")
        response = model.generate_content(prompt)

        # Check if the response has text content
        if response.candidates and response.candidates[0].content and response.candidates[0].content.parts:
            return response.candidates[0].content.parts[0].text
        else:
            print(f"      Warning: Gemini API returned an empty or malformed response. Debug info: {response}")
            return "Could not generate summary from Gemini API (empty response)."

    except Exception as e:
        print(f"      Error calling Google Gemini API: {type(e).__name__} - {e}")
        return "Could not get summary from Google Gemini API due to an error."

# Suppress potential warnings from yfinance or pandas that aren't critical for this script
warnings.filterwarnings('ignore')

# --- Professional Styling Configuration ---
# Set up professional matplotlib styling
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial', 'Helvetica']
plt.rcParams['font.size'] = 10
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['xtick.labelsize'] = 10
plt.rcParams['ytick.labelsize'] = 10
plt.rcParams['legend.fontsize'] = 10

# Professional color palette (Blue/Grey corporate theme)
COLORS = {
    'primary_blue': '#2E5090',
    'light_blue': '#4A7BA7',
    'accent_blue': '#6FA3C1',
    'dark_grey': '#333333',
    'light_grey': '#F5F5F5',
    'grid_grey': '#E0E0E0'
}

CHART_COLORS = ['#2E5090', '#4A7BA7', '#6FA3C1', '#8FB3D9', '#B8CCE4', '#D5DAED', '#E7E9F0']
sns.set_palette(CHART_COLORS)

# --- Beta Calculation Function ---
def calculate_beta(stock_ticker, benchmark_ticker='^GSPC', period='5y', interval='1wk'):
    """
    Calculates the beta for a given stock against a benchmark index.

    Args:
        stock_ticker (str): Ticker symbol of the stock.
        benchmark_ticker (str): Ticker symbol of the benchmark index (default: S&P 500).
        period (str): Period for historical data (e.g., '1y', '5y', 'max').
        interval (str): Data interval (e.g., '1d', '1wk', '1mo').

    Returns:
        float: Calculated beta, or None if data is insufficient or calculation fails.
    """
    try:
        stock_data = yf.download(stock_ticker, period=period, interval=interval, progress=False)
        benchmark_data = yf.download(benchmark_ticker, period=period, interval=interval, progress=False)

        if stock_data.empty or benchmark_data.empty:
            print(f"      Warning: Insufficient historical data from yfinance for beta calculation for {stock_ticker}.")
            return None

        stock_price_col = 'Adj Close' if 'Adj Close' in stock_data.columns else 'Close'
        if stock_price_col not in stock_data.columns:
            print(f"      Error: Neither 'Adj Close' nor 'Close' found for {stock_ticker}.")
            return None
        stock_prices = stock_data[stock_price_col].squeeze()

        benchmark_price_col = 'Adj Close' if 'Adj Close' in benchmark_data.columns else 'Close'
        if benchmark_price_col not in benchmark_data.columns:
            print(f"      Error: Neither 'Adj Close' nor 'Close' found for benchmark {benchmark_ticker}.")
            return None
        benchmark_prices = benchmark_data[benchmark_price_col].squeeze()

        merged_prices = pd.DataFrame({'Stock': stock_prices, 'Benchmark': benchmark_prices}).dropna()

        if len(merged_prices) < 2:
            print(f"      Warning: Not enough overlapping valid price data for beta calculation for {stock_ticker} after merging. Found {len(merged_prices)} points.")
            return None

        stock_returns = merged_prices['Stock'].pct_change().dropna()
        benchmark_returns = merged_prices['Benchmark'].pct_change().dropna()

        common_index = stock_returns.index.intersection(benchmark_returns.index)

        if common_index.empty:
            print(f"      Warning: No common dates for return data after intersection for beta calculation for {stock_ticker}.")
            return None

        stock_returns_aligned = stock_returns.loc[common_index]
        benchmark_returns_aligned = benchmark_returns.loc[common_index]

        stock_returns_arr = stock_returns_aligned.values.astype(float)
        benchmark_returns_arr = benchmark_returns_aligned.values.astype(float)

        finite_mask = np.isfinite(stock_returns_arr) & np.isfinite(benchmark_returns_arr)
        stock_returns_final = stock_returns_arr[finite_mask]
        benchmark_returns_final = benchmark_returns_arr[finite_mask]

        if len(stock_returns_final) < 2 or len(benchmark_returns_final) < 2:
            print(f"      Warning: Not enough aligned and finite return data points ({len(stock_returns_final)} for stock, {len(benchmark_returns_final)} for benchmark) for beta calculation for {stock_ticker}. Covariance/Variance requires at least 2 points. Returning None.")
            return None

        if np.all(np.isclose(stock_returns_final, stock_returns_final[0])):
            print(f"      Warning: Stock returns for {stock_ticker} are constant or nearly constant (all values approximately {stock_returns_final[0]:.6f}). Cannot calculate meaningful beta.")
            return None
        if np.all(np.isclose(benchmark_returns_final, benchmark_returns_final[0])):
            print(f"      Warning: Benchmark returns for {benchmark_ticker} are constant or nearly constant (all values approximately {benchmark_returns_final[0]:.6f}). Cannot calculate meaningful beta.")
            return None

        try:
            covariance_matrix = np.cov(np.atleast_2d(stock_returns_final), np.atleast_2d(benchmark_returns_final))
            covariance = covariance_matrix[0, 1]
            variance_benchmark = covariance_matrix[1, 1]
        except ValueError as ve:
            print(f"      Error within np.cov for {stock_ticker}: ValueError - {ve}")
            print(f"      This suggests a problem with the processed return data, possibly it became degenerate (e.g., only one element or all identical values despite prior checks).")
            return None
        except Exception as e:
            print(f"      Unexpected error during np.cov for {stock_ticker}: {type(e).__name__} - {e}")
            return None

        if variance_benchmark == 0 or np.isclose(variance_benchmark, 0) or np.isnan(variance_benchmark):
            print(f"      Warning: Variance of benchmark returns is zero, NaN, or very close to zero for {stock_ticker}. Cannot calculate beta.")
            return None
        if np.isnan(covariance):
            print(f"      Warning: Covariance of returns is NaN for {stock_ticker}. Cannot calculate beta.")
            return None

        calculated_beta = covariance / variance_benchmark
        return calculated_beta

    except Exception as e:
        print(f"      Error calculating beta for {stock_ticker}: {type(e).__name__} - {e}")
        return None

# --- 1. Your Portfolio Input ---
# Define the stocks in your portfolio and the number of shares you own.
# You can customize this dictionary with your actual holdings.
portfolio_input = {
    'AAPL': {'SharesOwned': 10},
    'MSFT': {'SharesOwned': 25},
    'JPM': {'SharesOwned': 20},
    'GOOGL': {'SharesOwned': 10},
    'PINS': {'SharesOwned': 10},
    'CRM': {'SharesOwned': 10},
    'PFE': {'SharesOwned': 10},
    'AMD': {'SharesOwned': 10}
}

# --- 2. Fetch Data from Yahoo Finance ---
portfolio_data_list = []
failed_tickers = []
benchmark_ticker = '^GSPC' # S&P 500 (standard benchmark)

print("Fetching stock data from Yahoo Finance...")
for ticker_symbol, details in portfolio_input.items():
    print(f"  Fetching data for {ticker_symbol}...")
    try:
        ticker = yf.Ticker(ticker_symbol)
        info = ticker.info

        current_price = info.get('regularMarketPrice', info.get('currentPrice'))
        market_cap = info.get('marketCap')
        long_name = info.get('longName', ticker_symbol)
        market = info.get('market', 'N/A') # Get market info

        # Get dividend yield (using trailingAnnualDividendYield as it's more common for current yield)
        dividend_yield = info.get('trailingAnnualDividendYield')

        beta = info.get('beta')
        if beta is None:
            calculated_beta = calculate_beta(ticker_symbol, benchmark_ticker=benchmark_ticker, period='5y', interval='1wk')
            beta = calculated_beta
            if beta is not None:
                print(f"    Calculated Beta for {ticker_symbol}: {beta:.4f}")
            else:
                print(f"    Could not calculate beta for {ticker_symbol}.")

        # Check if any essential data is still missing after fetching and calculation attempts
        if current_price is None or market_cap is None or beta is None:
            missing_fields = []
            if current_price is None: missing_fields.append('Current Price')
            if market_cap is None: missing_fields.append('Market Cap')
            if beta is None: missing_fields.append('Beta')

            print(f"    Warning: Missing essential data for {ticker_symbol}: {', '.join(missing_fields)}. Skipping.")
            failed_tickers.append(ticker_symbol)
            time.sleep(1) # Pause to avoid overwhelming API
            continue # Skip to the next ticker in the loop

        portfolio_data_list.append({
            'Ticker': ticker_symbol,
            'LongName': long_name,
            'SharesOwned': details['SharesOwned'],
            'CurrentPrice': current_price,
            'MarketCap': market_cap,
            'Market': market, # Store market
            'DividendYield': dividend_yield, # Store dividend yield
            'Beta': beta
        })
        time.sleep(1) # Pause to avoid overwhelming API
    except Exception as e:
        print(f"    Error fetching data for {ticker_symbol}: {type(e).__name__} - {e}. Skipping.")
        failed_tickers.append(ticker_symbol)
        time.sleep(1) # Pause to avoid overwhelming API

if not portfolio_data_list:
    print("No valid stock data fetched. Please check your ticker symbols, yfinance version, or internet connection.")
    exit() # Exit if no data was successfully fetched to prevent errors

portfolio_df = pd.DataFrame(portfolio_data_list)

# Calculate total value for each holding and market cap in billions
portfolio_df['TotalValue'] = portfolio_df['SharesOwned'] * portfolio_df['CurrentPrice']
portfolio_df['MarketCap_Billions'] = portfolio_df['MarketCap'] / 1_000_000_000

# Function to determine capitalization size
def get_capital_size(market_cap_billions):
    if market_cap_billions >= 200:
        return 'Mega-Cap'
    elif market_cap_billions >= 10:
        return 'Large-Cap'
    elif market_cap_billions >= 2:
        return 'Mid-Cap'
    else:
        return 'Small-Cap'

portfolio_df['Capitalization'] = portfolio_df['MarketCap_Billions'].apply(get_capital_size)

# --- 3. Calculate Portfolio Metrics ---
total_portfolio_value = portfolio_df['TotalValue'].sum()

# Calculate Portfolio Beta (Weighted Average Beta)
# Portfolio Beta = SUM( (Weight of Stock i) * (Beta of Stock i) )
portfolio_df['Weight'] = portfolio_df['TotalValue'] / total_portfolio_value
portfolio_beta = (portfolio_df['Weight'] * portfolio_df['Beta']).sum()

# Calculate Portfolio Dividend Yield (Weighted Average)
# Portfolio Dividend Yield = SUM( (Weight of Stock i) * (Dividend Yield of Stock i) )
# Handle cases where DividendYield might be None/NaN
portfolio_df['AdjustedDividendYield'] = portfolio_df['DividendYield'].fillna(0) # Treat None/NaN as 0 for calculation
portfolio_dividend_yield = (portfolio_df['Weight'] * portfolio_df['AdjustedDividendYield']).sum()


# --- 4. Display Portfolio Summary & Capture Text Output ---
# Redirect stdout to capture print statements
old_stdout = sys.stdout
redirected_output = io.StringIO()
sys.stdout = redirected_output

print("\n--- Portfolio Summary ---")
print(f"Total Portfolio Value: ${total_portfolio_value:,.2f}")
print(f"Portfolio Beta (Weighted Average): {portfolio_beta:.4f}")
print(f"Portfolio Dividend Yield (Weighted Average): {portfolio_dividend_yield:.4f}") # Display portfolio yield
print("\nIndividual Holdings:")
# Display updated DataFrame, removing 'Industry' and adding 'Market' and 'DividendYield'
print(portfolio_df[['Ticker', 'LongName', 'SharesOwned', 'CurrentPrice', 'TotalValue', 'Weight', 'Beta', 'Capitalization', 'Market', 'DividendYield']].to_string(index=False))
print("\n--- Additional Information ---")

# --- Gemini API Integration: Generate and Display Summary ---
llm_input_data = (
    f"Total Portfolio Value: ${total_portfolio_value:,.2f}\n"
    f"Portfolio Beta: {portfolio_beta:.4f}\n"
    f"Portfolio Dividend Yield: {portfolio_dividend_yield:.4f}\n\n"
    "Individual Holdings Data:\n" +
    portfolio_df[['Ticker', 'TotalValue', 'Weight', 'Beta', 'Capitalization', 'Market', 'DividendYield']].to_string(index=False)
)
print("\n--- Gemini-Generated Portfolio Health Summary ---")
raw_gemini_summary = get_gemini_summary(llm_input_data)

# --- Apply text wrapping ONLY to the Gemini summary ---
# Adjust 'width' as needed for the Gemini summary specifically
# A width of 90-100 characters usually works well for fontsize 6-8 on A4.
wrapped_gemini_summary = textwrap.fill(raw_gemini_summary, width=95)

# Print the wrapped Gemini summary to the captured output
print(wrapped_gemini_summary)
print("\n--- End of Gemini Summary ---")


print("\nAnalysis Complete.")

# Restore stdout
sys.stdout = old_stdout
captured_text_output = redirected_output.getvalue() # This now contains unwrapped parts + wrapped Gemini summary
print(captured_text_output) # Print to console as usual

# --- 5. Generate Professional Visualizations & Save to PDF ---
pdf_output_filename = 'Portfolio_Analysis_Report.pdf'

with PdfPages(pdf_output_filename) as pdf:
    # Page 1: Executive Summary with Metric Cards
    fig_summary = plt.figure(figsize=(8.5, 11), facecolor='white')
    ax_summary = fig_summary.add_subplot(111)
    ax_summary.axis('off')

    # Title
    ax_summary.text(0.5, 0.96, 'Portfolio Analysis Report',
                   ha='center', fontsize=20, fontweight='bold', color=COLORS['primary_blue'])

    # Date
    from datetime import datetime
    today = datetime.now().strftime('%B %d, %Y')
    ax_summary.text(0.5, 0.93, f'Prepared: {today}',
                   ha='center', fontsize=10, color=COLORS['dark_grey'], style='italic')

    # Summary Metrics Section
    metrics_text = f"""
PORTFOLIO SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Portfolio Value                    ${total_portfolio_value:,.2f}
Portfolio Beta (Weighted Average)        {portfolio_beta:.4f}
Portfolio Dividend Yield                 {portfolio_dividend_yield:.2%}
Number of Holdings                       {len(portfolio_df)}


KEY HOLDINGS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

    # Add top 5 holdings
    top_holdings = portfolio_df.nlargest(5, 'TotalValue')
    for idx, row in top_holdings.iterrows():
        metrics_text += f"\n{row['Ticker']:6} {row['LongName']:30} ${row['TotalValue']:>12,.2f}  ({row['Weight']:>6.1%})"

    metrics_text += f"\n\n\nPORTFOLIO INSIGHTS\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    metrics_text += wrapped_gemini_summary

    ax_summary.text(0.08, 0.88, metrics_text,
                   fontsize=9, verticalalignment='top', family='monospace',
                   bbox=dict(boxstyle='round', facecolor=COLORS['light_grey'], alpha=0.5, pad=1))

    pdf.savefig(fig_summary, bbox_inches='tight')
    plt.close(fig_summary)

    # Plot 1: Portfolio Allocation by Value
    fig1 = plt.figure(figsize=(10, 7), facecolor='white')
    ax1 = fig1.add_subplot(111)
    bars1 = sns.barplot(x='Ticker', y='TotalValue', data=portfolio_df, palette=CHART_COLORS, ax=ax1)
    style_chart(ax1, 'Portfolio Allocation by Value', 'Ticker', 'Total Value ($)')
    ax1.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1000:.0f}K'))
    fig1.patch.set_facecolor('white')
    plt.tight_layout()
    pdf.savefig(fig1, bbox_inches='tight')
    plt.close(fig1)

    # Plot 2: Dividend Yield Comparison
    fig2 = plt.figure(figsize=(10, 7), facecolor='white')
    ax2 = fig2.add_subplot(111)
    yield_df = portfolio_df.dropna(subset=['DividendYield'])
    if not yield_df.empty:
        bars2 = sns.barplot(x='Ticker', y='DividendYield', data=yield_df, palette=CHART_COLORS, ax=ax2)
        ax2.axhline(portfolio_dividend_yield, color=COLORS['primary_blue'], linestyle='--',
                   linewidth=2, label=f'Portfolio Avg: {portfolio_dividend_yield:.2%}')
        style_chart(ax2, 'Individual Stock Dividend Yields', 'Ticker', 'Dividend Yield (%)')
        ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:.1%}'))
        ax2.legend(loc='upper right', framealpha=0.9)
    fig2.patch.set_facecolor('white')
    plt.tight_layout()
    pdf.savefig(fig2, bbox_inches='tight')
    plt.close(fig2)

    # Plot 3: Portfolio Allocation by Market
    market_allocation = portfolio_df.groupby('Market')['TotalValue'].sum()
    if not market_allocation.empty:
        fig3 = plt.figure(figsize=(10, 8), facecolor='white')
        ax3 = fig3.add_subplot(111)
        wedges, texts, autotexts = ax3.pie(market_allocation, labels=market_allocation.index,
                                            autopct='%1.1f%%', startangle=140, colors=CHART_COLORS,
                                            textprops={'fontsize': 11, 'weight': 'bold'})
        for autotext in autotexts:
            autotext.set_color('white')
            autotext.set_fontweight('bold')
        ax3.set_title('Portfolio Allocation by Market', fontsize=14, fontweight='bold',
                     pad=20, color=COLORS['dark_grey'])
        fig3.patch.set_facecolor('white')
        plt.tight_layout()
        pdf.savefig(fig3, bbox_inches='tight')
        plt.close(fig3)
    else:
        print("\nWarning: No market data available for pie chart.")

    # Plot 4: Beta Distribution
    fig4 = plt.figure(figsize=(10, 6), facecolor='white')
    ax4 = fig4.add_subplot(111)
    sns.histplot(portfolio_df['Beta'].dropna(), bins=6, kde=True,
                color=COLORS['light_blue'], edgecolor=COLORS['primary_blue'], ax=ax4)
    style_chart(ax4, 'Distribution of Stock Betas', 'Beta', 'Number of Stocks')
    fig4.patch.set_facecolor('white')
    plt.tight_layout()
    pdf.savefig(fig4, bbox_inches='tight')
    plt.close(fig4)

    # Plot 5: 10-Year Portfolio Projection
    projection_years = 10
    growth_rate = 0.10
    projected_values = [total_portfolio_value]
    years = [0]

    for i in range(1, projection_years + 1):
        projected_values.append(projected_values[-1] * (1 + growth_rate))
        years.append(i)

    fig5 = plt.figure(figsize=(10, 7), facecolor='white')
    ax5 = fig5.add_subplot(111)
    ax5.plot(years, projected_values, marker='o', linestyle='-', linewidth=2.5,
            markersize=6, color=COLORS['primary_blue'], label='Projected Value')
    ax5.fill_between(years, projected_values, alpha=0.2, color=COLORS['light_blue'])
    style_chart(ax5, f'10-Year Portfolio Value Projection ({growth_rate*100:.0f}% Annual Growth)',
               'Years from Now', 'Projected Portfolio Value ($)')
    ax5.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1e6:.1f}M' if x >= 1e6 else f'${x/1000:.0f}K'))
    ax5.legend(loc='upper left', framealpha=0.9)
    fig5.patch.set_facecolor('white')
    plt.tight_layout()
    pdf.savefig(fig5, bbox_inches='tight')
    plt.close(fig5)

# Helper function for consistent chart styling
def style_chart(ax, title, xlabel, ylabel):
    """Apply consistent professional styling to charts."""
    ax.set_title(title, fontsize=14, fontweight='bold', pad=15, color=COLORS['dark_grey'])
    ax.set_xlabel(xlabel, fontsize=11, fontweight='bold', color=COLORS['dark_grey'])
    ax.set_ylabel(ylabel, fontsize=11, fontweight='bold', color=COLORS['dark_grey'])
    ax.grid(True, linestyle='-', alpha=0.2, color=COLORS['grid_grey'])
    ax.set_axisbelow(True)
    for spine in ax.spines.values():
        spine.set_color(COLORS['grid_grey'])
        spine.set_linewidth(0.5)

print(f"\nAll plots and summary text saved to {pdf_output_filename}")
print("\nAnalysis Complete.")
